sudo: required

services:
  - docker

language: minimal

env:
  - CONTAINER_IMAGE=ros:melodic \
    CONTAINER_NAME=industrial_training_ci

install:
  - docker pull $CONTAINER_IMAGE

script:
  - source .industrial_training_ci.bash && ci_run build_exercises \
      exercises/1.3/src \
      exercises/1.4/src \
      exercises/2.0/src \
      exercises/2.2/src \
      exercises/2.3/src \
      exercises/3.0/src \
      exercises/3.1/src \
      exercises/3.2/src \
      exercises/3.3/src \
      exercises/4.0/src \
      exercises/4.1/src \
      exercises/5.0/src \
      exercises/5.1/solution_ws/src \
      exercises/5.2/src \
      exercises/5.3/src \
      exercises/5.4/src \
      exercises/6.0/src \
      exercises/6.1/src \
      exercises/6.3/src \
      exercises/Descartes_Planning_and_Execution/solution_ws/src \
      exercises/Optimization_Based_Planning/solution_ws/src \
      exercises/Perception-Driven_Manipulation/solution_ws/src \
      exercises/python-pcl_ws/src

